### ISSUE TITLE
IllegalArgumentException: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by jcchikikomori** [PayMaya/PayMaya-Android-SDK-v2#2]
I was transitioning using your SDK from Version 1 to Version 2, and I got this error. Maybe your `requestCode` was higher than the framework allowed or higher than 16 bits of integer value

Reference: https://stackoverflow.com/a/33332468/6413072

**Comment by rjarce** [comment]
Hi @jcchikikomori , can you share the full stack trace for this exception? Thanks

**Comment by jcchikikomori** [comment]
> Hi @jcchikikomori , can you share the full stack trace for this exception? Thanks

Sorry i cannot, because i am working on a private project (disclosed). However, I found that the ButterKnife causes the issues which is not yet recognized the kotlin code yet. So change my code with dependencies

So the fix was my code itself. I changed `annotationProcessor` into `kapt`

```
build.gradle

buildscript {
    ext.kotlin_version = '1.3.61'
    repositories {
        google()
        jcenter()
        ...
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        ....
        classpath 'io.fabric.tools:gradle:1.31.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath "org.jlleitschuh.gradle:ktlint-gradle:9.2.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

```
app/build.gradle

apply plugin: 'com.android.application'
...

// kotlin related
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlinx-serialization'
apply plugin: "org.jlleitschuh.gradle.ktlint"

dependencies {
    ...
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.71'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3"
    implementation "ru.gildor.coroutines:kotlin-coroutines-okhttp:1.0"
    ...

    // BUTTERKNIFE
    implementation 'com.jakewharton:butterknife:10.2.0'
    kapt 'com.jakewharton:butterknife-compiler:10.2.0'
}
```

These changes may be needed for other devs with any current Java project

**Comment by jcchikikomori** [comment]
> Hi @jcchikikomori , can you share the full stack trace for this exception? Thanks

Here's my report from Crashlytics
```txt

Fatal Exception: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
       at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:660)
       at com.paymaya.sdk.android.checkout.internal.PayMayaCheckoutImpl.startCheckoutActivityForResult(PayMayaCheckoutImpl.kt:57)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter.executePaymaya(CheckoutPresenter.kt:300)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter.access$executePaymaya(CheckoutPresenter.kt:38)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter$cartCheckoutCashless$1.onNext(CheckoutPresenter.kt:374)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter$cartCheckoutCashless$1.onNext(CheckoutPresenter.kt:359)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:6732)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by jcchikikomori** [comment]
> Hi @jcchikikomori , can you share the full stack trace for this exception? Thanks

Here's my stack trace.

```txt
Fatal Exception: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
       at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:660)
       at com.paymaya.sdk.android.checkout.internal.PayMayaCheckoutImpl.startCheckoutActivityForResult(PayMayaCheckoutImpl.kt:57)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter.executePaymaya(CheckoutPresenter.kt:300)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter.access$executePaymaya(CheckoutPresenter.kt:38)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter$cartCheckoutCashless$1.onNext(CheckoutPresenter.kt:374)
       at ph.mobext.mcdelivery.ui.checkout.CheckoutPresenter$cartCheckoutCashless$1.onNext(CheckoutPresenter.kt:359)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:6732)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jcchikikomori** [comment]
> Hi @jcchikikomori , can you share the full stack trace for this exception? Thanks

Here's my stack trace.

```txt
Fatal Exception: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
       at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:660)
       at com.paymaya.sdk.android.checkout.internal.PayMayaCheckoutImpl.startCheckoutActivityForResult(PayMayaCheckoutImpl.kt:57)
       at ph.REDACTED.REDACTED.ui.checkout.CheckoutPresenter.executePaymaya(CheckoutPresenter.kt:300)
       at ph.REDACTED.REDACTED.ui.checkout.CheckoutPresenter.access$executePaymaya(CheckoutPresenter.kt:38)
       at ph.REDACTED.REDACTED.ui.checkout.CheckoutPresenter$cartCheckoutCashless$1.onNext(CheckoutPresenter.kt:374)**
       at ph.REDACTED.REDACTED.ui.checkout.CheckoutPresenter$cartCheckoutCashless$1.onNext(CheckoutPresenter.kt:359)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:6732)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by rjarce** [comment]
Thanks @jcchikikomori . Will drop some changes on the `requestCode` constants and a snapshot library sometime this week.

**Comment by ianv1** [comment]
@rjarce I am also facing the same issue. Have you fixed this?
https://stackoverflow.com/questions/25529865/java-lang-illegalargumentexception-can-only-use-lower-16-bits-for-requestcode
