### ISSUE TITLE
HTTP 401 Error on checking Payment Statuses unless client has a secret key

### ISSUE THREAD

**Issue by jcchikikomori** [PayMaya/PayMaya-Android-SDK-v2#9]
Hi. I have a problem with my migration from v1 to v2 of your Checkout
The client's merchant data has no Secret Key for PayMaya Checkout, so here's what happens

Reference:
https://hackmd.io/@paymaya-pg/Checkout#Get-Checkout---GET-httpspg-sandboxpaymayacomcheckoutv1checkoutscheckoutId

Setup:
```java
// Prepare PayMayaCheckout singleton
mPayMayaCheckout = PayMayaCheckout.Companion.newBuilder()
        .clientPublicKey(midPublicKey)
        .environment(PayMayaEnvironment.PRODUCTION)
        .logLevel(BuildConfig.DEBUG ? LogLevel.VERBOSE : LogLevel.ERROR)
        .build();
// Execute Checkout WebView
mPayMayaCheckout.startCheckoutActivityForResult(getMvpView().getActivity(), checkout);
```

Stack trace:
```txt
2020-08-26 18:12:39.019 17786-19008/ph.redacted.redacted.staging.debug E/PayMayaSDK: Backend response deserialization problem. Backend response: 401, Unauthorized
    kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 26: Encountered an unknown key message
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
        at kotlinx.serialization.json.internal.JsonReader.fail$default(JsonReader.kt:292)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeObjectIndex(StreamingJsonInput.kt:123)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeElementIndex(StreamingJsonInput.kt:88)
        at com.paymaya.sdk.android.common.models.GenericError$$serializer.deserialize(Unknown Source:19)
        at com.paymaya.sdk.android.common.models.GenericError$$serializer.deserialize(GenericError.kt:32)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.CoreKt.decode(Core.kt:80)
        at kotlinx.serialization.json.Json.parse(Json.kt:126)
        at com.paymaya.sdk.android.common.internal.SendRequestBaseUseCase.processHttpUnauthorizedResponse(SendRequestBaseUseCase.kt:91)
        at com.paymaya.sdk.android.common.internal.SendRequestBaseUseCase.processResponse(SendRequestBaseUseCase.kt:60)
        at com.paymaya.sdk.android.common.internal.SendRequestBaseUseCase.access$processResponse(SendRequestBaseUseCase.kt:36)
        at com.paymaya.sdk.android.common.internal.SendRequestBaseUseCase$run$2.invokeSuspend(SendRequestBaseUseCase.kt:44)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-08-26 18:12:39.159 17786-17786/ph.redacted.redacted.staging.debug E/PayMayaSDK: PayMaya Checkout result: FAILURE
2020-08-26 18:12:39.160 17786-17786/ph.redacted.redacted.staging.debug E/PayMayaSDK: com.paymaya.sdk.android.common.exceptions.InternalException: Backend response deserialization problem. Backend response: 401, Unauthorized
2020-08-26 18:12:39.263 17786-17786/ph.redacted.redacted.staging.debug E/StringFormatter: [ph.redacted.redacted.utils.StringFormatter.isReallyBlank(StringFormatter.java:48), ph.redacted.redacted.ui.checkout.CheckoutActivity.paramsUpdate(CheckoutActivity.java:1250), ph.redacted.redacted.ui.checkout.CheckoutActivity.onResume(CheckoutActivity.java:1558), android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413), android.app.Activity.performResume(Activity.java:7329), android.app.ActivityThread.performResumeActivity(ActivityThread.java:3802), android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3849), android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51), android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145), android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70), android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814), android.os.Handler.dispatchMessage(Handler.java:106), android.os.Looper.loop(Looper.java:198), android.app.ActivityThread.main(ActivityThread.java:6732), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)]
```

**Comment by rjarce** [comment]
Hi @jcchikikomori , the mobile SDKs only hit APIs that have a public scope. In line with this, the SDKs are configured to use a different endpoint for checking the Checkout status that works on a public scope. It's basically a dumbed-down version of the Get Checkout and Get Payments APIs (from Payment Vault) (it's not yet in the docs as we haven't formally released this as an API, but we're planning on releasing it eventually). So the user of the SDK only has to configure the public key.

Are you testing with the same public key you were previously loading on the v1 SDK, which has Checkout permissions?

**Comment by jcchikikomori** [comment]
> 
> Are you testing with the same public key you were previously loading on the v1 SDK, which has Checkout permissions?
>
Yes. The keys are still from version 1

**Comment by rjarce** [comment]
> > 
> > Are you testing with the same public key you were previously loading on the v1 SDK, which has Checkout permissions?
> >
> Yes. The keys are still from version 1
> 
> 

Hmm. Any chance you had a customized build of the v1 plugin? This looks like a key scope problem with the key you are using, can you email me with your merchant account so I can check?

**Comment by jcchikikomori** [comment]
> Hmm. Any chance you had a customized build of the v1 plugin? This looks like a key scope problem with the key you are using, can you email me with your merchant account so I can check?

Unfortunately, I don't have access to the merchant account since this is needed to be coordinated by the client. Someone from the company I worked on will coordinate to you soon on weekdays

**Comment by jcchikikomori** [comment]
@rjarce Hi. It seems that the merchant keys are working now on the latest SDK. I will close it for now
